--[[
    init.lua
    Created: 02/06/2023 18:34:12
    Description: Autogenerated script file for the map moon_test1.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local moon_test1 = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---moon_test1.Init
--Engine callback function
function moon_test1.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---moon_test1.Enter
--Engine callback function
function moon_test1.Enter(map)

  GAME:FadeIn(20)

end

---moon_test1.Exit
--Engine callback function
function moon_test1.Exit(map)


end

---moon_test1.Update
--Engine callback function
function moon_test1.Update(map)


end

---moon_test1.GameSave
--Engine callback function
function moon_test1.GameSave(map)


end

---moon_test1.GameLoad
--Engine callback function
function moon_test1.GameLoad(map)

  GAME:FadeIn(20)

end

function moon_test1.NPC_Enemy1(map)
  GAME:CutsceneMode(true)

  local chara = CH('Partner')
  local player = CH('PLAYER')
  UI:SetSpeaker(chara)

  GAME:WaitFrames(60)
  GROUND:CharSetEmote(chara, "question", 1)

  UI:WaitShowDialogue(STRINGS:Format(MapStrings['PartnerCutscene1']))
  GROUND:EntTurn(chara, Direction.Right)

  --UI:SetSpeakerEmotion("Surprised")
  --GROUND:CharSetEmote(chara, "shock", 1)
  --SOUND:PlayBattleSE("EVT_Emote_Shock_Bad")
  --GAME:WaitFrames(60)

  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PartnerCutscene2']))

  --UI:SetSpeaker(player)
  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PlayerCutscene1']))

  --UI:SetSpeaker(chara)
  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PartnerCutscene3']))

  --UI:SetSpeaker(player)
  --UI:SetSpeakerEmotion("Worried")
  --GROUND:CharSetEmote(player, "question", 1)
  --SOUND:PlayBattleSE("EVT_Emote_Confused")
  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PlayerCutscene2']))

  --UI:SetSpeaker(chara)
  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PartnerCutscene4']))

  --UI:SetSpeaker(player)
  ----UI:SetSpeakerEmotion("Question")
  --UI:SetSpeakerEmotion("Worried")
  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PlayerCutscene3']))

  --UI:SetSpeaker(chara)
  --Normal Happy sad inspired worried surprised shouting angry determined joyous teary-eyed crying stunned dizzy sigh special0-3
  --UI:SetSpeakerEmotion("Surprised")
  --GROUND:CharSetEmote(chara, "sweating", 1)
  --SOUND:PlayBattleSE("EVT_Emote_Sweating")
  --UI:WaitShowDialogue(STRINGS:Format(MapStrings['PartnerCutscene5']))
  --UI:WaitShowDialogue(STRINGS:Format("Test String"))


  UI:ResetSpeaker()
  GAME:CutsceneMode(false)
end

-------------------------------
-- Entities Callbacks
-------------------------------


return moon_test1

