--[[
    init.lua
    Created: 08/15/2022 20:22:20
    Description: Autogenerated script file for the map village_past.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local village_past = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---village_past.Init
--Engine callback function
function village_past.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  GAME:UnlockDungeon('forbidden_forest')

end

---village_past.Enter
--Engine callback function
function village_past.Enter(map)

  GAME:FadeIn(20)

end

---village_past.Exit
--Engine callback function
function village_past.Exit(map)


end

---village_past.Update
--Engine callback function
function village_past.Update(map)


end

---village_past.GameSave
--Engine callback function
function village_past.GameSave(map)


end

---village_past.GameLoad
--Engine callback function
function village_past.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function village_past.South_Exit_Touch(obj, activator)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  local dungeon_entrances = { 'forbidden_forest'}
  local ground_entrances = {{Flag=false, Zone='forbidden_forest',ID=0,Entry=0}}
  COMMON.ShowDestinationMenu(dungeon_entrances,ground_entrances)
end

return village_past

