--[[
    init.lua
    Created: 08/17/2022 15:25:54
    Description: Autogenerated script file for the map forbidden_forest.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local forbidden_forest = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---forbidden_forest.Init
--Engine callback function
function forbidden_forest.Init(zone)


end

---forbidden_forest.EnterSegment
--Engine callback function
function forbidden_forest.EnterSegment(zone, rescuing, segmentID, mapID)


end

---forbidden_forest.ExitSegment
--Engine callback function
function forbidden_forest.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---forbidden_forest.Rescued
--Engine callback function
function forbidden_forest.Rescued(zone, name, mail)


end

return forbidden_forest

